[workspace]
members = [
    "cep18",
    "cep18-test-contract",
    "tests",
]
default-members = [
    "cep18",
    "cep18-test-contract",
    "tests",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
